export const users = [
  {
    name: "Sheila Hughes",
    topic: "Exploring the wonders of nature",
    status: "Old",
    createdOn: "09/10/2022 08:15pm",
  },
  {
    name: "Gilliam Amelia",
    topic: "The power of positive thinking",
    status: "New",
    createdOn: "04/07/2024 07:00pm",
  },
  {
    name: "Caldwell Deana",
    topic: "The power of positive thinking",
    status: "New",
    createdOn: "11/30/2020 06:30pm",
  },
  {
    name: "Winnie Powers",
    topic: "The science behind a good night’s sleep",
    status: "New",
    createdOn: "06/05/2022 01:45pm",
  },
  {
    name: "Lula Bobbie",
    topic: "Steps to achieve financial independence",
    status: "New",
    createdOn: "02/28/2023 02:00pm",
  },
  {
    name: "Diana Keller",
    topic: "How to build strong relationships",
    status: "Old",
    createdOn: "01/15/2024 09:30am",
  },
  {
    name: "Farley Frances",
    topic: "The challenges of remote work and how to overcome them",
    status: "New",
    createdOn: "09/10/2022 08:15pm",
  },
  {
    name: "Eugenia Moon",
    topic: "The science behind a good night’s sleep",
    status: "Old",
    createdOn: "07/18/2021 11:00am",
  },
  {
    name: "Delgado Gibson",
    topic: "How to stay motivated during tough times",
    status: "Old",
    createdOn: "07/18/2021 11:00am",
  },
  {
    name: "Christie Maldonado",
    topic: "Understanding cryptocurrency and blockchain",
    status: "Old",
    createdOn: "03/22/2023 03:15pm",
  },
  {
    name: "Leona Martha",
    topic: "The benefits of regular exercise",
    status: "New",
    createdOn: "02/28/2023 02:00pm",
  },
  {
    name: "Harrell Andrea",
    topic: "The influence of social media on society",
    status: "Old",
    createdOn: "03/22/2023 03:15pm",
  },
  {
    name: "Hale Lindsey",
    topic: "The benefits of regular exercise",
    status: "Old",
    createdOn: "04/07/2024 07:00pm",
  },
  {
    name: "Elliott Sasha",
    topic: "The history and significance of space exploration",
    status: "Old",
    createdOn: "02/28/2023 02:00pm",
  },
  {
    name: "Hendricks Milagros",
    topic: "How to start your own business",
    status: "New",
    createdOn: "07/18/2021 11:00am",
  },
  {
    name: "Jeannine Beach",
    topic: "How to start your own business",
    status: "New",
    createdOn: "04/07/2024 07:00pm",
  },
  {
    name: "Cecile Jacklyn",
    topic: "How to navigate career changes effectively",
    status: "Old",
    createdOn: "07/18/2021 11:00am",
  },
  {
    name: "Isabelle Charity",
    topic: "How to improve productivity at work",
    status: "Old",
    createdOn: "06/05/2022 01:45pm",
  },
  {
    name: "Kidd Jeannette",
    topic: "Understanding the basics of programming",
    status: "New",
    createdOn: "02/28/2023 02:00pm",
  },
  {
    name: "Hurst Howell",
    topic: "Exploring cultural diversity around the world",
    status: "New",
    createdOn: "02/28/2023 02:00pm",
  },
  {
    name: "Kristina Hobbs",
    topic: "Steps to achieve financial independence",
    status: "New",
    createdOn: "07/18/2021 11:00am",
  },
  {
    name: "Fran Peters",
    topic: "The benefits of regular exercise",
    status: "New",
    createdOn: "02/28/2023 02:00pm",
  },
  {
    name: "Laurie Taylor",
    topic: "The importance of teamwork in the workplace",
    status: "New",
    createdOn: "02/28/2023 02:00pm",
  },
  {
    name: "Watson Essie",
    topic: "The art of effective communication",
    status: "New",
    createdOn: "04/07/2024 07:00pm",
  },
  {
    name: "Odom Kerr",
    topic: "The future of technology and AI",
    status: "Old",
    createdOn: "06/05/2022 01:45pm",
  },
  {
    name: "Hebert Shauna",
    topic: "The role of art and creativity in our lives",
    status: "Old",
    createdOn: "03/22/2023 03:15pm",
  },
  {
    name: "Blake Elnora",
    topic: "How to master a new skill",
    status: "Old",
    createdOn: "06/05/2022 01:45pm",
  },
  {
    name: "Chan Marva",
    topic: "The basics of personal branding",
    status: "Old",
    createdOn: "04/07/2024 07:00pm",
  },
  {
    name: "Griffin Jarvis",
    topic: "The art of effective communication",
    status: "New",
    createdOn: "05/14/2021 10:30am",
  },
  {
    name: "Lee Bailey",
    topic: "How to start your own business",
    status: "Old",
    createdOn: "01/15/2024 09:30am",
  },
];
